language: ruby
rvm:
  - 2.0.0
  - 2.1.0
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - gem install bundler -v '= 1.5.2'
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.sample config/gitlab.yml"
  - "cp config/pusher.yml.sample config/pusher.yml"
  - "RAILS_ENV=test bundle exec rake db:create db:migrate"
script: bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false